#!/usr/bin/env node

const yargs = require('yargs');
const { promisify } = require('util');
const { ECS, Credentials } = require('aws-sdk');

(async () => {

  try {

    console.log('process.argv', process.argv);
    const config = yargs(process.argv.slice(2))
      .option('access-key', { demandOption: true, type: 'string' })
      .option('secret-key', { demandOption: true, type: 'string' })
      .option('region', { demandOption: true, type: 'string' })
      .option('cluster', { demandOption: true, type: 'string' })
      .option('service', { demandOption: true, type: 'string' })
      .option('container', { demandOption: true, type: 'string' })
      .option('image', { demandOption: true, type: 'string' })
      .option('image-tag', { demandOption: true, type: 'string' })
      .option('target-variables', { demandOption: true, type: 'array', string: true })
      .option('wait', { default: false, type: 'boolean' })
      .argv;

    const ecs = new ECS({
      region: config.region,
      apiVersion: '2014-11-13',
      credentials: new Credentials(config.accessKey, config.secretKey)
    });

    const ecsDescribeServices = promisify(ecs.describeServices.bind(ecs));
    const ecsDescribeTaskDefinition = promisify(ecs.describeTaskDefinition.bind(ecs));
    const ecsRegisterTaskDefinition = promisify(ecs.registerTaskDefinition.bind(ecs));
    const ecsUpdateService = promisify(ecs.updateService.bind(ecs));
    const ecsWaitFor = promisify(ecs.waitFor.bind(ecs));

    const serviceDescriptions = await ecsDescribeServices({
      cluster: config.cluster,
      services: [config.service]
    });

    const taskDefinitionDescription = await ecsDescribeTaskDefinition({
      taskDefinition: serviceDescriptions.services[0].taskDefinition
    });

    const task = taskDefinitionDescription.taskDefinition;
    console.log(`Current task definition: ${task.taskDefinitionArn}`);

    console.log(`config.targetVariables: ${config.targetVariables}`);
    const containerEnvironmentVariables = (config.targetVariables || [])
      .map(keyValueString => {
        const parts = keyValueString.split('=');
        return { name: parts[0], value: parts[1] };
      });
    console.log(`containerEnvironmentVariables: ${JSON.stringify(containerEnvironmentVariables)}`);

    const newTaskDefinition = {
      family: task.family,
      taskRoleArn: task.taskRoleArn,
      executionRoleArn: task.executionRoleArn,
      networkMode: task.networkMode,
      volumes: task.volumes,
      placementConstraints: task.placementConstraints,
      requiresCompatibilities: task.requiresCompatibilities,
      cpu: task.cpu,
      memory: task.memory,
      containerDefinitions: task.containerDefinitions.map(cd => {
        if (cd.name !== config.container) {
          return cd;
        }

        return {
          ...cd,
          image: `${config.image}:${config.imageTag}`
          // environment: containerEnvironmentVariables
        };
      })
    };

    const newTaskDefinitionDescription = await ecsRegisterTaskDefinition(newTaskDefinition);

    const registeredTask = newTaskDefinitionDescription.taskDefinition;
    console.log(`New task definition: ${registeredTask.taskDefinitionArn}`);

    await ecsUpdateService({
      cluster: config.cluster,
      service: config.service,
      taskDefinition: registeredTask.taskDefinitionArn
    });

    if (config.wait) {
      console.log('Waiting for service stability...');
      await ecsWaitFor('servicesStable', {
        cluster: config.cluster,
        services: [config.service],
      });
    }

    console.log('DONE!');

  } catch (error) {
    console.error(error);
    process.exit(1);
  }

})();
